### ISSUE TITLE
Loading a script should default its type to "script"

### ISSUE THREAD

**Issue by ItsGravix** [phaserjs/phaser#5994]
## Version

* Phaser Version: v3.60.0-beta.4

* Operating system: Windows 11

* Browser: Google Chrome

## Description

Loading a script should default its type to "script" to prevent older code from breaking.
If a type is not provided, this error will be thrown:

```
Uncaught Error: Invalid Loader.false key
    at ScriptFile.File (phaser.js:107085:19)
    at new ScriptFile (phaser.js:116182:14)
    at LoaderPlugin.script (phaser.js:116289:22)
    at EventEmitter.<anonymous> (<anonymous>:116:21)
    at EventEmitter.emit (phaser.js:197:35)
    at LoaderPlugin.<anonymous> (<anonymous>:273:37)
    at LoaderPlugin.emit (phaser.js:200:35)
    at LoaderPlugin.loadComplete (phaser.js:108625:14)
    at LoaderPlugin.fileProcessComplete (phaser.js:108591:18)
    at ImageFile.onProcessComplete (phaser.js:107408:21)
```

## Example Test Code

Non-working code:
`scene.load.script('RoomScene', 'assets/RoomScene.js');`

Working Code:
`scene.load.script('RoomScene', 'assets/RoomScene.js', 'script');`

**Comment by vforsh** [comment]
Ha, I was just going to report this issue 

Here is the live example - https://codesandbox.io/s/wandering-microservice-stecg?file=/src/index.ts

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
