### ISSUE TITLE
example "Nested Layers" not work

### ISSUE THREAD

**Issue by liuhongxuan23** [phaserjs/phaser#6024]
## Version
* Phaser Version: 3.55.2

## Example Test Code
https://phaser.io/examples/v3/view/game-objects/layer/nested-layers

## Additional Information
phaser.min.js:1 Uncaught TypeError: t.removeFromDisplayList is not a function
    at initialize.addChildCallback (phaser.min.js:1:250547)
    at Object.t.exports [as Add] (phaser.min.js:1:807053)
    at initialize.add (phaser.min.js:1:127944)
    at Example.create (<anonymous>:35:23)
    at initialize.create (phaser.min.js:1:491015)
    at initialize.loadComplete (phaser.min.js:1:490466)
    at initialize.o.emit (phaser.min.js:1:7809)
    at initialize.loadComplete (phaser.min.js:1:944358)
    at initialize.fileProcessComplete (phaser.min.js:1:944058)
    at t.onProcessComplete (phaser.min.js:1:21253)

**Comment by photonstorm** [comment]
This is a 3.60 feature, so you need to view it using the 'Dev Build' of Phaser: http://labs.phaser.io/view.html?src=src/game%20objects/layer/nested%20layers.js&v=dev
