### ISSUE TITLE
Cannot read properties of null (reading 'sys' and 'exists')

### ISSUE THREAD

**Issue by darrylthom** [phaserjs/phaser#6242]
## Version

* Phaser Version: v3.60.0-beta.11

* Operating system: Windows 11

* Browser: Chrome

## Description

When I unload the game, it is throwing the following errors:

1) Related to removeFromDisplayList function:
ERROR TypeError: Cannot read properties of null (reading 'exists')
    at Image.removeFromDisplayList (phaser.js:32470:25)
    at Image.destroy (phaser.js:32554:14)
    at TextureManager.destroy (phaser.js:198052:20)
    at EventEmitter.emit (phaser.js:218:33)
    at Game.runDestroy (phaser.js:17111:21)

2) Related to this.systemScene.sys.destroy():
ERROR TypeError: Cannot read properties of null (reading 'sys')
    at SceneManager.destroy (phaser.js:180541:26)
    at Game.runDestroy (phaser.js:17109:20)
    at Game.step (phaser.js:16865:25)
    at TimeStep.step (phaser.js:17880:14)
    at stepTimeout (phaser.js:30892:19)
    at timer (zone.js:2561:41)
    at ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25459:33)
    at ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)

The 2nd error mentioned seems to be looping and these errors did not show up before in beta 10.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
