### ISSUE TITLE
when i destoryed the sprite

### ISSUE THREAD

**Issue by liuzhongq** [phaserjs/phaser#6470]
aser.js:171936 Uncaught TypeError: Cannot read properties of undefined (reading 'body')
    at World.remove (phaser.js:171936:1)
    at Object.destroy (phaser.js:179463:1)
    at Project.onCompose (game.js:479:1)
    at Tween.onComplete (game.js:310:1)
    at Tween.dispatchTweenEvent (phaser.js:58162:1)
    at Tween.nextState (phaser.js:57743:1)
    at Tween.update (phaser.js:58103:1)
    at TweenManager.update (phaser.js:178102:1)
    at EventEmitter.emit (phaser.js:1694:1)
    at Systems.step (phaser.js:41844:1)
    at SceneManager.update (phaser.js:84646:1)
    at Game.step (phaser.js:137314:1)
    at TimeStep.step (phaser.js:75507:1)
    at step (phaser.js:75715:1)
r

**Comment by liuzhongq** [comment]
This problem has been good before

**Comment by photonstorm** [comment]
Code sample please.

**Comment by liuzhongq** [comment]
> Code sample please.

![image](https://user-images.githubusercontent.com/32831306/231921095-b6d32fdd-ba19-4f95-a9c4-0f010f359626.png)

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.
