### ISSUE TITLE
Uncaught TypeError: s.renderWebGL is not a function

### ISSUE THREAD

**Issue by FilterUnfiltered** [phaserjs/phaser#6567]
## Version

* Browser: Chromium 114.0.5735.198

## Description

When attempting to apply a mask to an arcade image object, the console gives the following error:

```js
Uncaught TypeError: s.renderWebGL is not a function
    at initialize.preRenderWebGL (phaser.min.js:1:492042)
    at initialize.render (phaser.min.js:1:521596)
    at initialize.render (phaser.min.js:1:773418)
    at initialize.render (phaser.min.js:1:189563)
    at initialize.render (phaser.min.js:1:388712)
    at initialize.step (phaser.min.js:1:733432)
    at initialize.step (phaser.min.js:1:448455)
    at e (phaser.min.js:1:445807)
```

## Example Test Code

```js
	const obj = this.physics.add.image(50, 50, imageName);

	obj.setCircle(48, obj.body.Width, obj.body.Height);

	obj.setMask(new Phaser.Display.Masks.GeometryMask(this, mask));
```

## Additional Information

I could be using the engine wrong somehow since this is my first time using phaser, but I don't think it should be failing internally regardless, right?

**Comment by FilterUnfiltered** [comment]
I used it wrong
