### ISSUE TITLE
I want to know how to fix bug about chrome in windows, about lockdown-run.js.

### ISSUE THREAD

**Issue by 2016WUJI01** [phaserjs/phaser#6640]
I have some bug with chrome in windows, when i run the example, my console show some bug
 ```Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3
```

and 
```
lockdown-more.js:99 Protecting intrinsics failed: ReferenceError: harden is not defined
  at lockdown-more.js:69:13
  at Set.forEach (<anonymous>)
  at protectIntrinsics (lockdown-more.js:44:22)
  at lockdown-more.js:97:5
```

I don't konw how i can solve that, my node: v18.15.0, my yarn:1.22.19.
And also, when i use safari with mac, i never got this bugs.

**Comment by 2016WUJI01** [comment]
sorry for this, it might bug with some other things.

**Comment by photonstorm** [comment]
It's a bug in MetaMask. They've fixed it but not deployed the new version of their extension yet.

**Comment by 2016WUJI01** [comment]
yes, sorry for my mistake, i try to use phaser.js but in my chrome with windows, it have not success.there have some thing wrong about still wating on run depencies: @face_mesh_solution_simd_wasm_bin_js
